strfirst = input('Введите первую строку\n')
strsecond = input('Введите вторую строку\n')
print('первая введенная вами строка:\n' +strfirst)
print(f'вторая введенная вами строка:\n{strsecond}')
print('Их длина соответсвенно ' +str(len(strfirst))  + ' и ' +str(len(strsecond)) + ' символов')
print('первый символ первой строки :\n' +strfirst[0])
print('последний символ последней строки :\n' +strsecond[len(strsecond) - 1])
print(f"'{strfirst}' равна '{strsecond}'? " +str(strfirst == strsecond))
print(f"'{strfirst}' содержится ли в '{strsecond}'? " +str(strfirst in strsecond))
print("А наоборот? " +str(strsecond in strfirst) )